change consul parameters
livepeer/stream-tester pull request #59
Opened 2020-11-10 18:27 UTC by iameli

Instead of hitting a service, we can create our own custom service record and forward traffic wherever we want. So this sets us up to route `/hls/{playbackId}` to `https://mdw-staging-mist-server-0.livepeer.monster`, which is ready for global replication on ingest URLs.

2020-11-10 18:38 UTC, iameli commented
Maybe `-mist-url` isn't the best name if we already have `-mist-host` and `-mist-port`. Could call it `-external-mist-url` or `-consul-mist-url` or something.

2020-11-10 23:33 UTC, darkdarkdragon requested changes
Small fix

2020-11-10 23:33 UTC, darkdarkdragon commented on internal/app/mistapiconnector/mistapiconnector_app.go
> +				traefikKeyPathServices+streamKey+"/loadbalancer/servers/0/url",
```suggestion
				traefikKeyPathServices+streamKey+"/loadbalancer/servers/0/url",
				mc.mistURL,
```

2020-11-10 23:33 UTC, darkdarkdragon commented on cmd/mist-api-connector/mist-api-connector.go
> +	mistURL := fs.String("mist-url", "", "external URL of this Mist instance (to be put in Consul) (ex: https://mist-server-0.livepeer.live)")
```suggestion
	mistURL := fs.String("consul-mist-url", "", "external URL of this Mist instance (to be put in Consul) (ex: https://mist-server-0.livepeer.live)")
```

2020-11-10 23:35 UTC, darkdarkdragon commented
> So this sets us up to route /hls/{playbackId} to https://mdw-staging-mist-server-0.livepeer.monster, which is ready for global replication on ingest URLs.

Interesting - I thought internal addresses should be used. But if it works than OK.

2020-11-11 00:35 UTC, iameli commented
Yeah, I tested it with `https://icanhazip.com` and it worked perfectly. Surprised me too but very useful. We can basically configure Traefik as an HTTPS proxy into anything we want now. cc @yondonfu, maybe useful for your T reverse-proxy work?

2020-11-11 00:37 UTC, merged